# Generated by Django 3.0.2 on 2020-01-08 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200108_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='adc',
            new_name='top',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 11, 52, 13, 557533), verbose_name='date published'),
        ),
    ]
