# Generated by Django 3.0.2 on 2020-01-09 18:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200109_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_is_drafted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_player_size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 13, 22, 8, 869227), verbose_name='date published'),
        ),
    ]
