# Generated by Django 3.0.2 on 2020-01-10 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200110_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_league',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 14, 43, 56, 938522), verbose_name='date published'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('team_league', 'team_name')},
        ),
    ]
