# Generated by Django 3.0.2 on 2020-01-10 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200110_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 14, 51, 35, 778996), verbose_name='date published'),
        ),
    ]
